# Generated by Django 4.2 on 2023-05-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Materiais', 'Materiais'), ('Ferramentas', 'Ferramentas'), ('Diversos', 'Diversos'), ('Selecione a Categoria', ' -- ')], default='Selecione a Categoria', max_length=100),
        ),
    ]
