# Generated by Django 4.1.7 on 2023-05-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
